
# Netlify configuration file
[build]
  command = "npm run build"
  publish = "dist"

# Redirect rules for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
